## Importing libraries

In [9]:
import numpy as np

In [10]:
mlist = [1,2,3]

In [11]:
arr = np.array(mlist)

In [12]:
arr

array([1, 2, 3])

In [13]:
my_matrice = [[1,2,3], [4,5,6],[7,8,9]]
my_matrice

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_matrice)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.ones(4)

array([1., 1., 1., 1.])

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

linspace(Start, stop, evenly-stopped numbers between start and stop)

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [26]:
## .eye ==> same no. of rows and columns
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
#Pass one argument to get one-dimensional array
np.random.rand(5)

array([0.28379098, 0.40133382, 0.87687316, 0.20898345, 0.80482859])

In [28]:
#pass two arguments for two-dimensional array
np.random.rand(5,5)

array([[0.91466663, 0.52763114, 0.61231765, 0.66311175, 0.87511203],
       [0.86375325, 0.31077253, 0.36663871, 0.52011658, 0.84725503],
       [0.87177108, 0.52325214, 0.63617303, 0.31079764, 0.54259345],
       [0.69564174, 0.13942264, 0.04143746, 0.42367711, 0.76582353],
       [0.31864503, 0.29842291, 0.87910826, 0.53277907, 0.32778123]])

In [29]:
#numbers for gaussian distribution
np.random.randn(2)

array([-0.09297943, -0.91146908])

In [30]:
np.random.randn(4,4)

array([[ 0.75365788,  0.09459558,  0.61307228,  0.03500651],
       [-1.74841478,  2.05421137,  0.01682958, -0.90449484],
       [-1.07803847, -0.01860466,  0.15012017,  0.07642722],
       [ 0.62318139, -1.04605132, -1.18792622,  0.19103609]])

In [31]:
#returns random number between low and high
np.random.randint(1, 100)

8

In [32]:
#3rd argument is the size
np.random.randint(1, 100, 10)

array([ 1, 34, 37, 83, 19, 67, 62, 94, 23, 15])

In [33]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.shape

(25,)

In [35]:
arr.max()

24

In [36]:
arr.min()

0

In [37]:
arr.argmax()

24

In [39]:
arr.shape

(25,)

In [42]:
arr_2d = np.arange(50).reshape(5,10)

In [43]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [44]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## NumPy Operations

In [46]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [50]:
##scalar operations
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [51]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [52]:
# first value is 0...0 divide by 0 gives warning for 1st value
arr / arr

/Users/pratiksharaval/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
1 / arr

/Users/pratiksharaval/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [54]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
## Universal Array Functions

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [57]:
np.max(arr)

10

In [58]:
arr.max()

10

In [59]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [60]:
np.log(arr)

/Users/pratiksharaval/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Pandas

In [61]:
my_list = [10, 20, 30]
labels = ['a', 'b', 'c']
arr = np.array(my_list)
d = {'a': 10, 'b': 20, 'c': 30}

In [62]:
pd.Series(data = my_list)

0    10
1    20
2    30
dtype: int64

In [65]:
pd.Series(data = my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [66]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [67]:
pd.Series(arr, labels)

a    10
b    20
c    30
dtype: int64

In [68]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [70]:
pd.Series(data=labels)

0    a
1    b
2    c
dtype: object

In [71]:
ser1 = pd.Series([1,2,3,4],['USA', 'India', 'China', 'Iran'])

In [72]:
ser1

USA      1
India    2
China    3
Iran     4
dtype: int64

In [ ]:
ser2 = pd.Series()

# DataFrames

In [73]:
from numpy.random import randn

In [74]:
np.random.seed(101)

In [76]:
df = pd.DataFrame(randn(5,4), ['A','B','C','D','E'], ['W','X','Y','Z'])
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [77]:
#Way 1
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [78]:
type(df['W'])

pandas.core.series.Series

In [79]:
type(df)

pandas.core.frame.DataFrame

In [80]:
#Way2
df.W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [81]:
df[['W', 'Z']]

W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [82]:
df['new_col'] = df['W'] + df['Y']

In [83]:
df

W         X         Y         Z   new_col
A  0.302665  1.693723 -1.706086 -1.159119 -1.403420
B -0.134841  0.390528  0.166905  0.184502  0.032064
C  0.807706  0.072960  0.638787  0.329646  1.446493
D -0.497104 -0.754070 -0.943406  0.484752 -1.440510
E -0.116773  1.901755  0.238127  1.996652  0.121354

In [87]:
#for removing column
df.drop('new_col', axis=1,inplace=True)

In [88]:
df

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [89]:
df.drop('E')

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752

In [90]:
# way-1 to grab a row ---location based index
df.loc['A']

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [91]:
# way-1 to grab a row -- number based index
df.iloc[0]

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [92]:
df.loc['B','Y']

0.16690463609281317

In [93]:
df.loc[['A','B'],['X','Y']]

X         Y
A  1.693723 -1.706086
B  0.390528  0.166905

In [94]:
#returns boolean value
df > 0

W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [95]:
booldf = df>0

In [96]:
df[booldf]

W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [97]:
df['W']>0

A     True
B    False
C     True
D    False
E    False
Name: W, dtype: bool

In [98]:
df['W']

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [99]:
df[df['W']>0]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [100]:
df[df['Z']<0]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119

Multiple conditions. Pandas doesn't work with and and or. We have to use <b>"& |" 

In [101]:
df[(df['Y']<0) & (df['Z']<0)]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119

In [102]:
df[(df['W']>0) | (df['X']>0)]

W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
E -0.116773  1.901755  0.238127  1.996652

Set vs Reset Index

In [103]:
#do this and use inplace=True generally
df.reset_index()

index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [104]:
new_index = 'CA NT WY OR CO'.split()

In [105]:
new_index

['CA', 'NT', 'WY', 'OR', 'CO']

In [106]:
df['states'] = new_index

In [107]:
df

W         X         Y         Z states
A  0.302665  1.693723 -1.706086 -1.159119     CA
B -0.134841  0.390528  0.166905  0.184502     NT
C  0.807706  0.072960  0.638787  0.329646     WY
D -0.497104 -0.754070 -0.943406  0.484752     OR
E -0.116773  1.901755  0.238127  1.996652     CO

In [108]:
df.set_index('states')

W         X         Y         Z
states                                        
CA      0.302665  1.693723 -1.706086 -1.159119
NT     -0.134841  0.390528  0.166905  0.184502
WY      0.807706  0.072960  0.638787  0.329646
OR     -0.497104 -0.754070 -0.943406  0.484752
CO     -0.116773  1.901755  0.238127  1.996652

### Index levels

In [111]:
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside, inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [112]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [113]:
inside

[1, 2, 3, 1, 2, 3]

In [115]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [116]:
df = pd.DataFrame(randn(6,2), hier_index,['A', 'B'])

In [117]:
df

A         B
G1 1 -0.993263  0.196800
   2 -1.136645  0.000366
   3  1.025984 -0.156598
G2 1 -0.031579  0.649826
   2  2.154846 -0.610259
   3 -0.755325 -0.346419

In [118]:
df.loc['G1']

A         B
1 -0.993263  0.196800
2 -1.136645  0.000366
3  1.025984 -0.156598

In [119]:
df.index.names = ['Groups', 'Num']

In [120]:
df

A         B
Groups Num                    
G1     1   -0.993263  0.196800
       2   -1.136645  0.000366
       3    1.025984 -0.156598
G2     1   -0.031579  0.649826
       2    2.154846 -0.610259
       3   -0.755325 -0.346419

In [123]:
df.loc['G2']

A         B
Num                    
1   -0.031579  0.649826
2    2.154846 -0.610259
3   -0.755325 -0.346419

In [124]:
df.loc['G2'].loc[2]

A    2.154846
B   -0.610259
Name: 2, dtype: float64

In [125]:
df.loc['G2'].loc[2]['B']

-0.6102588558227414

In [126]:
#cross-section
df

A         B
Groups Num                    
G1     1   -0.993263  0.196800
       2   -1.136645  0.000366
       3    1.025984 -0.156598
G2     1   -0.031579  0.649826
       2    2.154846 -0.610259
       3   -0.755325 -0.346419

In [127]:
df.loc['G1']

A         B
Num                    
1   -0.993263  0.196800
2   -1.136645  0.000366
3    1.025984 -0.156598

In [128]:
df.xs('G1')

A         B
Num                    
1   -0.993263  0.196800
2   -1.136645  0.000366
3    1.025984 -0.156598

In [129]:
df.xs(1, level='Num')

A         B
Groups                    
G1     -0.993263  0.196800
G2     -0.031579  0.649826

# Missing data 

In [131]:
d = {'A':[1,2,np.nan], 'B':[5,np.nan,np.nan], 'C':[1,2,3]}

In [132]:
df = pd.DataFrame(d)
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [134]:
df.dropna(axis=1)

C
0  1
1  2
2  3

In [135]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [138]:
df.dropna(thresh=2)

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [139]:
df.fillna(value='FILLVALUE')

A          B  C
0          1          5  1
1          2  FILLVALUE  2
2  FILLVALUE  FILLVALUE  3

In [140]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

## GroupBy

In [143]:
data = {'Company': ['GOOG','GOOG','MSFT','MSFT','FB','FB'],
        'Person': ['Sam', 'Charlie', 'Amy', 'Vanessa', 'Carl', 'Sarah'],
        'Sales': [200,120,340,124,243,350]}

In [144]:
df = pd.DataFrame(data)

In [145]:
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [146]:
df.groupby('Company')

In [147]:
byComp = df.groupby('Company')

In [148]:
byComp

In [149]:
byComp.mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0

In [150]:
byComp.sum()

Sales
Company       
FB         593
GOOG       320
MSFT       464

In [151]:
byComp.std()

Sales
Company            
FB        75.660426
GOOG      56.568542
MSFT     152.735065

In [152]:
byComp.sum().loc['FB']

Sales    593
Name: FB, dtype: int64

In [153]:
df.groupby('Company').count()

Person  Sales
Company               
FB            2      2
GOOG          2      2
MSFT          2      2

In [155]:
df.groupby('Company').max()

Person  Sales
Company                
FB         Sarah    350
GOOG         Sam    200
MSFT     Vanessa    340

In [156]:
df.groupby('Company').min()

Person  Sales
Company                
FB          Carl    243
GOOG     Charlie    120
MSFT         Amy    124

In [157]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [158]:
df.groupby('Company').describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

In [159]:
df.groupby('Company').describe().transpose()['FB']

Sales  count      2.000000
       mean     296.500000
       std       75.660426
       min      243.000000
       25%      269.750000
       50%      296.500000
       75%      323.250000
       max      350.000000
Name: FB, dtype: float64

## Merging, joining, concatenating

# Operations

In [160]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [161]:
df['col2'].unique()

array([444, 555, 666])

In [162]:
df['col2'].nunique()

3

In [163]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [164]:
df[df['col1']>2]

col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [166]:
df['col1']>2

0    False
1    False
2     True
3     True
Name: col1, dtype: bool

In [167]:
df[(df['col1']>2) & (df['col2']==444)]

col1  col2 col3
3     4   444  xyz

In [168]:
def times2(x):
    return x*2

In [169]:
df['col1'].apply(times2)

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [170]:
df['col3'].apply(len)

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [171]:
df['col2'].apply(lambda x: x*2)

0     888
1    1110
2    1332
3     888
Name: col2, dtype: int64

In [172]:
df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [173]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [174]:
df.sort_values('col2')

col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [175]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [176]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz

In [177]:
data = {'A':['foo','foo','foo','bar','bar','bar'],
     'B':['one','one','two','two','one','one'],
       'C':['x','y','x','y','x','y'],
       'D':[1,3,2,5,4,1]}

df = pd.DataFrame(data)

In [178]:
df

A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [181]:
df.pivot_table(values='D', index=['A', 'B'], columns=['C'])

C          x    y
A   B            
bar one  4.0  1.0
    two  NaN  5.0
foo one  1.0  3.0
    two  2.0  NaN

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Importing Dataset

In [2]:
dataset = pd.read_csv('Data.csv')

In [3]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
pip install -U scikit-learn

Requirement already up-to-date: scikit-learn in /Users/pratiksharaval/opt/anaconda3/lib/python3.7/site-packages (0.23.1)
Note: you may need to restart the kernel to use updated packages.


## Taking care of missing data

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [8]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding Categorical data